### ISSUE TITLE
Suspect this line should assign "2004" as this is what my vehicle is and it's responding with "1994 1/2"

### ISSUE THREAD

**Issue by nurbers** [laszlodaniel/ChryslerCCDSCIScanner#10]
https://github.com/laszlodaniel/ChryslerScanner/blob/dc3ddec03143a20d7d1a833325280bcdd2e7f342/GUI/ChryslerScanner/SCIPCM.cs#L3568

**Comment by nurbers** [comment]
Nice, correct date now shown.  Didn't realize more complicated than just changing date.  Appreciatively

**Comment by laszlodaniel** [comment]
Thanks for testing!
I think "1994 1/2" and "1991-1995" is just a workaround for specific controller(s). Those slots were meant to be 2004 and 2005. A better solution would be not to filter by CumminsSelected switch, but assign 2004 and 2005 by default.
