### ISSUE TITLE
Firmware for ATmega.

### ISSUE THREAD

**Issue by SMoskalev** [laszlodaniel/ChryslerCCDSCIScanner#2]
Hello!

Very interesting project! I assemble the board, but can find no firmware for ATmegas CPU. Where can I download it?

**Comment by laszlodaniel** [comment]
Hello! You can find the .hex file it in the "/AVR/Compiled/" folder inside the .zip file.

**Comment by SMoskalev** [comment]
I see only one hex and eep set of files, is it for ATmega 2560 or 8u2?

**Comment by laszlodaniel** [comment]
It's for the 2560, the 8U2 comes pre-flashed with the appropriate firmware but I can update the .zip file in a minute with both firmwares that I use.

**Comment by SMoskalev** [comment]
Thank you! Don't forget to note fuse configuration for both CPU.

**Comment by laszlodaniel** [comment]
Fair point, I'll do that too shortly. Thank you!
