### ISSUE TITLE
Feature request: Log responses as CSV

### ISSUE THREAD

**Issue by dino2gnt** [laszlodaniel/ChryslerCCDSCIScanner#9]
When sending repeated commands, such as fetching parameters via SCI CMD 14 in the Engine Tools interface, it would be most excellent if the scanner application could optionally write the responses to CSV so that a user could see how the values change over time (and potentially graph them)

For example, i send a request for 0x1412, 0x1415, and 0x1416:
```
3D 00 0C 26 05 03 02 14 12 02 14 15 02 14 16 F8
```
The responses could be written out:
```
epochmillis,1412,1415,1416
epochmillis,03,11,00
epochmillis,03,10,00
epochmillis,05,11,00
[ ... ]
epochmillis,05,11,00
epochmillis,1412,1415,1416
epochmillis,08,16,00
[ ... ]
```
Where `epochmillis` is a milisecond epoch timestamp, and the header `epochmillis,1412,1415,1416` could be logged on an interval every X samples or every X seconds, or similar.

**Comment by laszlodaniel** [comment]
This CSV format is a good idea. Wouldn't a single header be enough, though?

```
Timestamp,1412,1415,1416
00:00:29.447,03,11,00
00:00:29.598,03,10,00
00:00:29.735,05,11,00
```

Also which time format is preferable? First I used integer milliseconds while developing the logging feature, then moved on to this "hours:minutes:seconds.milliseconds" format.

**Comment by dino2gnt** [comment]
>Wouldn't a single header be enough, though?

Personal preference.  Having the header in multiple places or at an interval is helpful when dealing with long-running CSV.
 
>Also which time format is preferable? 

Dealer's choice :)  I have no opinions on format beyond epoch time being strictly numerical and thus simpler to parse and math on.

**Comment by laszlodaniel** [comment]
```
pcmlog_20220928_115214.csv

Milliseconds,1405,1406,1407,1408,1409,140A,140B,140C
542682,174,255,255,64,0,191,234,45
542882,174,255,255,64,0,191,234,45
543083,174,255,255,64,0,191,234,45
543284,174,255,255,64,0,191,234,45
543484,174,255,255,64,0,191,234,45
543685,174,255,255,64,0,191,234,45
543886,174,255,255,64,0,191,234,45
544087,174,255,255,64,0,191,234,45
544287,174,255,255,64,0,191,234,45
544488,174,255,255,64,0,191,234,45
544689,174,255,255,64,0,191,234,45
544889,174,255,255,64,0,191,234,45
545090,174,255,255,64,0,191,234,45
545291,174,255,255,64,0,191,234,45
545491,174,255,255,64,0,191,234,45
545692,174,255,255,64,0,191,234,45
545893,174,255,255,64,0,191,234,45
546094,174,255,255,64,0,191,234,45
546294,174,255,255,64,0,191,234,45
```

Progress:
The header starts with Milliseconds label, followed by requests in 14XX hexadecimal format. Only 1 header line is used for now.
Then each line starts with milliseconds elapsed as an integer number, then comma separated bytes in decimal format.
New CSV-file is created when header line changes, otherwise lines are appended to the current session, even after stopping.

Let me know if this is good for testing!

**Comment by dino2gnt** [comment]
Looks fantastic!  Is there a build I can download to test?

**Comment by laszlodaniel** [comment]
Thanks! There are now new GUI and scanner firmware updates available. Check Tools / Update menu.
